const base = {
  name: "Base",
  image: "https://wiki.dominionstrategy.com/images/2/21/Dominion2.jpg",
  cards: [
    {
      name: "Cellar",
      category: ["Action"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/1c/Cellar.jpg",
    },
    {
      name: "Chapel",
      category: ["Action"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/29/Chapel.jpg",
    },
    {
      name: "Moat",
      category: ["Action", "Reaction"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/fe/Moat.jpg",
    },
    {
      name: "Harbinger",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/32/Harbinger.jpg",
    },
    {
      name: "Merchant",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/78/Merchant.jpg",
    },
    {
      name: "Vassal",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/0b/Vassal.jpg",
    },
    {
      name: "Village",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/5a/Village.jpg",
    },
    {
      name: "Workshop",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/50/Workshop.jpg",
    },
    {
      name: "Bureaucrat",
      category: ["Action", "Attack"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/4d/Bureaucrat.jpg",
    },
    {
      name: "Gardens",
      category: ["Victory"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/8c/Gardens.jpg",
    },
    {
      name: "Militia",
      category: ["Action", "Attack"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/a/a0/Militia.jpg",
    },
    {
      name: "Moneylender",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/70/Moneylender.jpg",
    },
    {
      name: "Poacher",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/a/a0/Poacher.jpg",
    },
    {
      name: "Remodel",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/2e/Remodel.jpg",
    },
    {
      name: "Smithy",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/36/Smithy.jpg",
    },
    {
      name: "Throne Room",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d1/Throne_Room.jpg",
    },
    {
      name: "Bandit",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/46/Bandit.jpg",
    },
    {
      name: "Council Room",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/e0/Council_Room.jpg",
    },
    {
      name: "Festival",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/ec/Festival.jpg",
    },
    {
      name: "Laboratory",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/0c/Laboratory.jpg",
    },
    {
      name: "Library",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/98/Library.jpg",
    },
    {
      name: "Market",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/7e/Market.jpg",
    },
    {
      name: "Mine",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/8e/Mine.jpg",
    },
    {
      name: "Sentry",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/4c/Sentry.jpg",
    },
    {
      name: "Witch",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/f3/Witch.jpg",
    },
    {
      name: "Artisan",
      category: ["Action"],
      cost: 6,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/1d/Artisan.jpg",
    },
  ],
};

const seaside = {
  name: "Seaside",
  image: "https://wiki.dominionstrategy.com/images/8/84/Seaside2.jpg",
  cards: [
    {
      name: "Haven",
      category: ["Action", "Duration"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c9/Haven.jpg",
    },
    {
      name: "Lighthouse",
      category: ["Action", "Duration"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/4f/Lighthouse.jpg",
    },
    {
      name: "Native Village",
      category: ["Action"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/67/Native_Village.jpg",
    },
    {
      name: "Astrolabe",
      category: ["Treasure", "Duration"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/1b/Astrolabe.jpg",
    },
    {
      name: "Fishing Village",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/3/3b/Fishing_Village.jpg",
    },
    {
      name: "Lookout",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c6/Lookout.jpg",
    },
    {
      name: "Monkey",
      category: ["Action", "Duration"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/30/Monkey.jpg",
    },
    {
      name: "Sea Chart",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/a/a7/Sea_Chart.jpg",
    },
    {
      name: "Smugglers",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/05/Smugglers.jpg",
    },
    {
      name: "Warehouse",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/6d/Warehouse.jpg",
    },
    {
      name: "Blockade",
      category: ["Action", "Duration", "Attack"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/df/Blockade.jpg",
    },
    {
      name: "Caravan",
      category: ["Action", "Duration"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c8/Caravan.jpg",
    },
    {
      name: "Cutpurse",
      category: ["Action", "Attack"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/7d/Cutpurse.jpg",
    },
    {
      name: "Island",
      category: ["Action", "Victory"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/fd/Island.jpg",
    },
    {
      name: "Sailor",
      category: ["Action", "Duration"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/b/bd/Sailor.jpg",
    },
    {
      name: "Salvager",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/89/Salvager.jpg",
    },
    {
      name: "Tide Pools",
      category: ["Action", "Duration"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/de/Tide_Pools.jpg",
    },
    {
      name: "Treasure Map",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/61/Treasure_Map.jpg",
    },
    {
      name: "Bazaar",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/f7/Bazaar.jpg",
    },
    {
      name: "Corsaid",
      category: ["Action", "Duration", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/ea/Corsair.jpg",
    },
    {
      name: "Merchant Ship",
      category: ["Action", "Duration"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/92/Merchant_Ship.jpg",
    },
    {
      name: "Outpost",
      category: ["Action", "Duration"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/b/b4/Outpost.jpg",
    },
    {
      name: "Pirate",
      category: ["Action", "Duration", "Reaction"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/ec/Pirate.jpg",
    },
    {
      name: "Sea Witch",
      category: ["Action", "Duration", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/14/Sea_Witch.jpg",
    },
    {
      name: "Tactician",
      category: ["Action", "Duration"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/ed/Tactician.jpg",
    },
    {
      name: "Treasury",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/fd/Treasury.jpg",
    },
    {
      name: "Wharf",
      category: ["Action", "Duration"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/cc/Wharf.jpg",
    },
  ],
};

const prosperity = {
  name: "Prosperity",
  image: "https://wiki.dominionstrategy.com/images/9/97/Prosperity.jpg",
  cards: [
    {
      name: "Loan",
      category: ["Treasure"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/11/Loan.jpg",
    },
    {
      name: "Trade Route",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/a/a7/Trade_Route.jpg",
    },
    {
      name: "Watchtower",
      category: ["Action", "Reaction"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c2/Watchtower.jpg",
    },
    {
      name: "Bishop",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/b/b4/Bishop.jpg",
    },
    {
      name: "Monument",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/a/ad/Monument.jpg",
    },
    {
      name: "Quarry",
      category: ["Treasure"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/65/Quarry.jpg",
    },
    {
      name: "Talisman",
      category: ["Treasure"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/cf/Talisman.jpg",
    },
    {
      name: "Workder's Village",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/1/12/Worker%27s_Village.jpg",
    },
    {
      name: "City",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/30/City.jpg",
    },
    {
      name: "Contraband",
      category: ["Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/58/Contraband.jpg",
    },
    {
      name: "Counting House",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/5d/Counting_House.jpg",
    },
    {
      name: "Mint",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/b/bc/Mint.jpg",
    },
    {
      name: "Mountebank",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/89/Mountebank.jpg",
    },
    {
      name: "Rabble",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/f1/Rabble.jpg",
    },
    {
      name: "Royal Seal",
      category: ["Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/dd/Royal_Seal.jpg",
    },
    {
      name: "Vault",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/62/Vault.jpg",
    },
    {
      name: "Venture",
      category: ["Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/ef/Venture.jpg",
    },
    {
      name: "Goons",
      category: ["Action", "Attack"],
      cost: 6,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/e2/Goons.jpg",
    },
    {
      name: "Hoard",
      category: ["Treasure"],
      cost: 6,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d1/Hoard.jpg",
    },
    {
      name: "Grand Market",
      category: ["Action"],
      cost: 6,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/81/Grand_Market.jpg",
    },
    {
      name: "Bank",
      category: ["Treasure"],
      cost: 7,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/78/Bank.jpg",
    },
    {
      name: "Expand",
      category: ["Action"],
      cost: 7,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/dc/Expand.jpg",
    },
    {
      name: "Forge",
      category: ["Action"],
      cost: 7,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d7/Forge.jpg",
    },
    {
      name: "King's Court",
      category: ["Action"],
      cost: 7,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/8d/King%27s_Court.jpg",
    },
    {
      name: "Peddler",
      category: ["Action"],
      cost: 8,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/6f/Peddler.jpg",
    },
  ],
};

const hinterlands = {
  name: "Hinterlands",
  image: "https://wiki.dominionstrategy.com/images/2/23/Hinterlands2.jpg",
  cards: [
    {
      name: "Crossroads",
      category: ["Action"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/cd/Crossroads.jpg",
    },
    {
      name: "Fool's Gold",
      category: ["Treasure", "Reaction"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/ed/Fool%27s_Gold.jpg",
    },
    {
      name: "Develop",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/f7/Develop.jpg",
    },
    {
      name: "Guard Dog",
      category: ["Action", "Reaction"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c7/Guard_Dog.jpg",
    },
    {
      name: "Oasis",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/fc/Oasis.jpg",
    },
    {
      name: "Scheme",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/8d/Scheme.jpg",
    },
    {
      name: "Tunnel",
      category: ["Victory", "Reaction"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c2/Tunnel.jpg",
    },
    {
      name: "Jack of All Trades",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/8/82/Jack_of_All_Trades.jpg",
    },
    {
      name: "Nomads",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/a/a0/Nomads.jpg",
    },
    {
      name: "Spice Merchant",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/e2/Spice_Merchant.jpg",
    },
    {
      name: "Trader",
      category: ["Action", "Reaction"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/12/Trader.jpg",
    },
    {
      name: "Trail",
      category: ["Action", "Reaction"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/6b/Trail.jpg",
    },
    {
      name: "Weaver",
      category: ["Action", "Reaction"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/6c/Weaver.jpg",
    },
    {
      name: "Berserker",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/cc/Berserker.jpg",
    },
    {
      name: "Cartographer",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d6/Cartographer.jpg",
    },
    {
      name: "Cauldron",
      category: ["Treasure", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/72/Cauldron.jpg",
    },
    {
      name: "Haggler",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/96/Haggler.jpg",
    },
    {
      name: "Highway",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/29/Highway.jpg",
    },
    {
      name: "Inn",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/1f/Inn.jpg",
    },
    {
      name: "Margrave",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/06/Margrave.jpg",
    },
    {
      name: "Souk",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/e1/Souk.jpg",
    },
    {
      name: "Stables",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/35/Stables.jpg",
    },
    {
      name: "Wheelwright",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d6/Wheelwright.jpg",
    },
    {
      name: "Witch's Hut",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/b/bf/Witch%27s_Hut.jpg",
    },
    {
      name: "Border Village",
      category: ["Action"],
      cost: 6,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/dd/Border_Village.jpg",
    },
    {
      name: "Farmland",
      category: ["Victory"],
      cost: 6,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/ea/Farmland.jpg",
    },
  ],
};

const empires = {
  name: "Empires",
  image: "https://wiki.dominionstrategy.com/images/0/0c/Empires.jpg",
  cards: [
    {
      name: "Engineer",
      category: ["Action"],
      cost: 0,
      debt: 4,
      image: "https://wiki.dominionstrategy.com/images/a/ab/Engineer.jpg",
    },
    {
      name: "City Quarter",
      category: ["Action"],
      cost: 0,
      debt: 8,
      image: "https://wiki.dominionstrategy.com/images/4/4e/City_Quarter.jpg",
    },
    {
      name: "Overlord",
      category: ["Action", "Command"],
      cost: 0,
      debt: 8,
      image: "https://wiki.dominionstrategy.com/images/5/5e/Overlord.jpg",
    },
    {
      name: "Royal Blacksmith",
      category: ["Action"],
      cost: 0,
      debt: 8,
      image:
        "https://wiki.dominionstrategy.com/images/c/cb/Royal_Blacksmith.jpg",
    },
    {
      name: "Encampment / Plunder",
      category: ["Action", "Treasure"],
      cost: 2,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/9/94/Encampment_Plunder.jpg",
    },
    {
      name: "Patrician / Emporium",
      category: ["Action"],
      cost: 2,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/0/0b/Patrician_Emporium.jpg",
    },
    {
      name: "Settlers / Bustling Village",
      category: ["Action"],
      cost: 2,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/4/48/Settlers_Bustling_Village.jpg",
    },
    {
      name: "Castles",
      category: ["Castle", "Victory", "Treasure", "Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/df/Castles.jpg",
    },
    {
      name: "Catapult / Rocks",
      category: ["Action", "Attack", "Treasure"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/75/Catapult_Rocks.jpg",
    },
    {
      name: "Chariot Race",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/7c/Chariot_Race.jpg",
    },
    {
      name: "Enchantress",
      category: ["Action", "Attack", "Duration"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/b/bb/Enchantress.jpg",
    },
    {
      name: "Farmers' Market",
      category: ["Action", "Gathering"],
      cost: 3,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/3/37/Farmers%27_Market.jpg",
    },
    {
      name: "Gladiator / Fortune",
      category: ["Action", "Treasure"],
      cost: 3,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/5/5d/Gladiator_Fortune.jpg",
    },
    {
      name: "Sacrifice",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/51/Sacrifice.jpg",
    },
    {
      name: "Temple",
      category: ["Action", "Gathering"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/9f/Temple.jpg",
    },
    {
      name: "Villa",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/f7/Villa.jpg",
    },
    {
      name: "Archive",
      category: ["Action", "Duration"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/26/Archive.jpg",
    },
    {
      name: "Capital",
      category: ["Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/eb/Capital.jpg",
    },
    {
      name: "Charm",
      category: ["Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/de/Charm.jpg",
    },
    {
      name: "Crown",
      category: ["Action", "Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/91/Crown.jpg",
    },
    {
      name: "Forum",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/15/Forum.jpg",
    },
    {
      name: "Groundskeeper",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/33/Groundskeeper.jpg",
    },
    {
      name: "Legionary",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/64/Legionary.jpg",
    },
    {
      name: "Wild Hunt",
      category: ["Action", "Gathering"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/48/Wild_Hunt.jpg",
    },
  ],
  events: [
    "Triumph",
    "Annex",
    "Donate",
    "Advance",
    "Delve",
    "Tax",
    "Banquet",
    "Ritual",
    "Salt the Earth",
    "Wedding",
    "Windfall",
    "Conquest",
    "Dominate",
  ],
  landmarks: [
    "Aqueduct",
    "Arena",
    "Bandit Fort",
    "Basilica",
    "Baths",
    "Battlefield",
    "Colonnade",
    "Defiled Shrine",
    "Fountain",
    "Keep",
    "Labyrinth",
    "Mountain Pass",
    "Museum",
    "Obelisk",
    "Orchard",
    "Palace",
    "Tomb",
    "Tower",
    "Triumphal Arch",
    "Wall",
    "Wolf Den",
  ],
};

const allies = {
  name: "Allies",
  image: "https://wiki.dominionstrategy.com/images/a/ab/Allies.jpg",
  cards: [
    {
      name: "Bauble",
      category: ["Treasure", "Liaison"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/2e/Bauble.jpg",
    },
    {
      name: "Sycophant",
      category: ["Action", "Liaison"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/4b/Sycophant.jpg",
    },
    {
      name: "Townsfolk",
      category: ["Townsfolk", "Action"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/83/Townsfolk.jpg",
    },
    {
      name: "Augurs",
      category: ["Augur", "Action", "Attack"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c3/Augurs.jpg",
    },
    {
      name: "Clashes",
      category: ["Clash", "Action", "Attack", "Duration", "Victory"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/ca/Clashes.jpg",
    },
    {
      name: "Forts",
      category: ["Fort", "Action", "Duration", "Victory"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/74/Forts.jpg",
    },
    {
      name: "Importer",
      category: ["Action", "Duration", "Liaison"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/a/a2/Importer.jpg",
    },
    {
      name: "Merchant Campe",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c3/Merchant_Camp.jpg",
    },
    {
      name: "Odysseys",
      category: ["Odyssey", "Action", "Duration", "Treasure", "Victory"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d1/Odysseys.jpg",
    },
    {
      name: "Sentinel",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/90/Sentinel.jpg",
    },
    {
      name: "Underling",
      category: ["Action", "Liaison"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c6/Underling.jpg",
    },
    {
      name: "Wizards",
      category: ["Wizard", "Action", "Liaison", "Duration", "Attack"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/3d/Wizards.jpg",
    },
    {
      name: "Broker",
      category: ["Action", "Liaison"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/32/Broker.jpg",
    },
    {
      name: "Carpenter",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/51/Carpenter.jpg",
    },
    {
      name: "Courier",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/6f/Courier.jpg",
    },
    {
      name: "Innkeeper",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/01/Innkeeper.jpg",
    },
    {
      name: "Royal Galley",
      category: ["Action", "Duration"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/95/Royal_Galley.jpg",
    },
    {
      name: "Town",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/8b/Town.jpg",
    },
    {
      name: "Barbarian",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/99/Barbarian.jpg",
    },
    {
      name: "Capital City",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/28/Capital_City.jpg",
    },
    {
      name: "Contract",
      category: ["Treasure", "Duration", "Liaison"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/b/bb/Contract.jpg",
    },
    {
      name: "Emissary",
      category: ["Action", "Liaison"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/99/Emissary.jpg",
    },
    {
      name: "Galleria",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/23/Galleria.jpg",
    },
    {
      name: "Guildmaster",
      category: ["Action", "Liaison"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/b/ba/Guildmaster.jpg",
    },
    {
      name: "Highwayman",
      category: ["Action", "Duration", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/7c/Highwayman.jpg",
    },
    {
      name: "Hunter",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/2a/Hunter.jpg",
    },
    {
      name: "Modify",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d8/Modify.jpg",
    },
    {
      name: "Skirmisher",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/7f/Skirmisher.jpg",
    },
    {
      name: "Specialist",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/41/Specialist.jpg",
    },
    {
      name: "Swap",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/50/Swap.jpg",
    },
    {
      name: "Marquis",
      category: ["Action"],
      cost: 6,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/41/Marquis.jpg",
    },
  ],
  allies: [
    "Architects' Guild",
    "Band of Nomads",
    "Cave Dwellers",
    "Circle of Witches",
    "City-state",
    "Coastal Haven",
    "Crafters' Guild",
    "Desert Guides",
    "Family of Inventors",
    "Fellowship of Scribes",
    "Forest Dwellers",
    "Gang of Pickpockets",
    "Island Folk",
    "League of Bankers",
    "League of Shopkeepers",
    "Market Towns",
    "Mountain Folk",
    "Order of Astrologers",
    "Order of Masons",
    "Peaceful Cult",
    "Plateau Shepherds",
    "Trappers' Lodge",
    "Woodworkers' Guild",
  ],
};

const plunder = {
  name: "Plunder",
  image: "https://wiki.dominionstrategy.com/images/0/0a/Plunder_%28expansion%29.jpg",
  cards: [
    {
      name: "Cage",
      category: ["Treasure", "Duration"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/60/Cage.jpg",
    },
    {
      name: "Grotto",
      category: ["Action", "Duration"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/2a/Grotto.jpg",
    },
    {
      name: "Jewelled Egg",
      category: ["Treasure"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/fd/Jewelled_Egg.jpg",
    },
    {
      name: "Search",
      category: ["Action", "Duration"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/01/Search.jpg",
    },
    {
      name: "Shaman",
      category: ["Action"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d1/Shaman.jpg",
    },
    {
      name: "Secluded Shrine",
      category: ["Action", "Duration"],
      cost: 3,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/8/80/Secluded_Shrine.jpg",
    },
    {
      name: "Siren",
      category: ["Action", "Duration", "Attack"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/6b/Siren.jpg",
    },
    {
      name: "Stowaway",
      category: ["Action", "Duration", "Reaction"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/66/Stowaway.jpg",
    },
    {
      name: "Taskmaster",
      category: ["Action", "Duration"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/cc/Taskmaster.jpg",
    },
    {
      name: "Abundance",
      category: ["Treasure", "Duration"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/a/ac/Abundance.jpg",
    },
    {
      name: "Cabin Boy",
      category: ["Action", "Duration"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d1/Cabin_Boy.jpg",
    },
    {
      name: "Crucible",
      category: ["Treasure"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/9a/Crucible.jpg",
    },
    {
      name: "Flagship",
      category: ["Action", "Duration", "Command"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/28/Flagship.jpg",
    },
    {
      name: "Fortune Hunter",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/1a/Fortune_Hunter.jpg",
    },
    {
      name: "Gondola",
      category: ["Treasure", "Duration"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/eb/Gondola.jpg",
    },
    {
      name: "Harbor Village",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/5c/Harbor_Village.jpg",
    },
    {
      name: "Landing Party",
      category: ["Action", "Duration"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/0d/Landing_Party.jpg",
    },
    {
      name: "Mapmaker",
      category: ["Action", "Reaction"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/7e/Mapmaker.jpg",
    },
    {
      name: "Maroon",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/4a/Maroon.jpg",
    },
    {
      name: "Rope",
      category: ["Treasure", "Duration"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/2a/Rope.jpg",
    },
    {
      name: "Swamp Shacks",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/64/Swamp_Shacks.jpg",
    },
    {
      name: "Tools",
      category: ["Treasure"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/cc/Tools.jpg",
    },
    {
      name: "Buried Treasure",
      category: ["Treasure", "Duration"],
      cost: 5,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/4/4c/Buried_Treasure.jpg",
    },
    {
      name: "Crew",
      category: ["Action", "Duration"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/da/Crew.jpg",
    },
    {
      name: "Cutthroat",
      category: ["Action", "Duration", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/22/Cutthroat.jpg",
    },
    {
      name: "Enlarge",
      category: ["Action", "Duration"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/90/Enlarge.jpg",
    },
    {
      name: "Figurine",
      category: ["Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/cf/Figurine.jpg",
    },
    {
      name: "First Mate",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/79/First_Mate.jpg",
    },
    {
      name: "Frigate",
      category: ["Action", "Duration", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/1c/Frigate.jpg",
    },
    {
      name: "Longship",
      category: ["Action", "Duration"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/8d/Longship.jpg",
    },
    {
      name: "Mining Road",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/9b/Mining_Road.jpg",
    },
    {
      name: "Pendant",
      category: ["Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c2/Pendant.jpg",
    },
    {
      name: "Pickaxe",
      category: ["Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d3/Pickaxe.jpg",
    },
    {
      name: "Pilgrim",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/61/Pilgrim.jpg",
    },
    {
      name: "Quartermaster",
      category: ["Action", "Duration"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/3c/Quartermaster.jpg",
    },
    {
      name: "Silver Mine",
      category: ["Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/ca/Silver_Mine.jpg",
    },
    {
      name: "Trickster",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/8/8a/Trickster.jpg",
    },
    {
      name: "Wealthy Village",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/2/20/Wealthy_Village.jpg",
    },
    {
      name: "Sack of Loot",
      category: ["Treasure"],
      cost: 6,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/51/Sack_of_Loot.jpg",
    },
    {
      name: "King's Cache",
      category: ["Treasure"],
      cost: 7,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/e7/King%27s_Cache.jpg",
    },
  ],
  events: [
    "Bury",
    "Avoid",
    "Deliver",
    "Peril",
    "Rush",
    "Foray",
    "Launch",
    "Mirror",
    "Prepare",
    "Scrounge",
    "Journey",
    "Maelstrom",
    "Looting",
    "Invasion",
    "Prosper",
  ],
  traits: [
    "Cheap",
    "Cursed",
    "Fated",
    "Fawning",
    "Friendly",
    "Hasty",
    "Inherited",
    "Inspiring",
    "Nearby",
    "Patient",
    "Pious",
    "Reckless",
    "Rich",
    "Shy",
    "Tireless",
  ],
};

const adventures = {
  name: "Adventures",
  image: "https://wiki.dominionstrategy.com/images/d/da/Adventures.jpg",
  cards: [
    {
      name: "Coin of the Realm",
      category: ["Treasure", "Reserve"],
      cost: 2,
      debt: 0,
      image:
        "https://wiki.dominionstrategy.com/images/7/76/Coin_of_the_Realm.jpg",
    },
    {
      name: "Page",
      category: ["Action", "Traveller", "Attack", "Duration"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/60/Page.jpg",
    },
    {
      name: "Peasant",
      category: ["Action", "Traveller", "Attack", "Reserve"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/70/Peasant.jpg",
    },
    {
      name: "Ratcatcher",
      category: ["Action", "Reserve"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/1d/Ratcatcher.jpg",
    },
    {
      name: "Raze",
      category: ["Action"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d3/Raze.jpg",
    },
    {
      name: "Amulet",
      category: ["Action", "Duration"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/50/Amulet.jpg",
    },
    {
      name: "Caravan Guard",
      category: ["Action", "Duration", "Reaction"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/fa/Caravan_Guard.jpg",
    },
    {
      name: "Dungeon",
      category: ["Action", "Duration"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/1e/Dungeon.jpg",
    },
    {
      name: "Gear",
      category: ["Action", "Duration"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/ec/Gear.jpg",
    },
    {
      name: "Guide",
      category: ["Action", "Reserve"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/e/e1/Guide.jpg",
    },
    {
      name: "Duplicate",
      category: ["Action", "Reserve"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/59/Duplicate.jpg",
    },
    {
      name: "Magpie",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/10/Magpie.jpg",
    },
    {
      name: "Messenger",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/3c/Messenger.jpg",
    },
    {
      name: "Miser",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/f6/Miser.jpg",
    },
    {
      name: "Port",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d0/Port.jpg",
    },
    {
      name: "Ranger",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/37/Ranger.jpg",
    },
    {
      name: "Transmogrify",
      category: ["Action", "Reserve"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/a/a9/Transmogrify.jpg",
    },
    {
      name: "Artificer",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/01/Artificer.jpg",
    },
    {
      name: "Bridge Troll",
      category: ["Action", "Duration", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/77/Bridge_Troll.jpg",
    },
    {
      name: "Distant Lands",
      category: ["Action", "Reserve", "Victory"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/3e/Distant_Lands.jpg",
    },
    {
      name: "Giant",
      category: ["Action", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/4c/Giant.jpg",
    },
    {
      name: "Haunted Woods",
      category: ["Action", "Duration", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/54/Haunted_Woods.jpg",
    },
    {
      name: "Lost City",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/9a/Lost_City.jpg",
    },
    {
      name: "Relic",
      category: ["Treasure", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d3/Relic.jpg",
    },
    {
      name: "Royal Carriage",
      category: ["Action", "Reserve"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/cf/Royal_Carriage.jpg",
    },
    {
      name: "Storyteller",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/6a/Storyteller.jpg",
    },
    {
      name: "Swamp Hag",
      category: ["Action", "Duration", "Attack"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/db/Swamp_Hag.jpg",
    },
    {
      name: "Treasure Trove",
      category: ["Treasure"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/2/22/Treasure_Trove.jpg",
    },
    {
      name: "Wine Merchant",
      category: ["Action", "Reserve"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/b/b2/Wine_Merchant.jpg",
    },
    {
      name: "Hireling",
      category: ["Action", "Duration"],
      cost: 6,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/9/91/Hireling.jpg",
    },
  ],
  events: [
    "Alms",
    "Borrow",
    "Quest",
    "Save",
    "Scouting Party",
    "Travelling Fair",
    "Bonfire",
    "Expedition",
    "Ferry",
    "Plan",
    "Mission",
    "Pilgrimage",
    "Ball",
    "Raid",
    "Seaway",
    "Trade",
    "Lost Arts",
    "Training",
    "Inheritance",
    "Pathfinding",
  ],
};

const risingSun = {
  name: "Rising Sun",
  image: "https://wiki.dominionstrategy.com/images/4/4a/Rising_Sun.jpg",
  cards: [
    {
      name: "Mountain Shrine",
      category: ["Action", "Omen"],
      cost: 0,
      debt: 5,
      image:
        "https://wiki.dominionstrategy.com/images/5/5a/Mountain_Shrine.jpg",
    },
    {
      name: "Daimyo",
      category: ["Action", "Command"],
      cost: 0,
      debt: 6,
      image: "https://wiki.dominionstrategy.com/images/0/04/Daimyo.jpg",
    },
    {
      name: "Artist",
      category: ["Action"],
      cost: 0,
      debt: 8,
      image: "https://wiki.dominionstrategy.com/images/4/4f/Artist.jpg",
    },
    {
      name: "Fishmonger",
      category: ["Action", "Shadow"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/54/Fishmonger.jpg",
    },
    {
      name: "Snake Witch",
      category: ["Action", "Attack"],
      cost: 2,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d6/Snake_Witch.jpg",
    },
    {
      name: "Aristocrat",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/01/Aristocrat.jpg",
    },
    {
      name: "Craftsman",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/75/Craftsman.jpg",
    },
    {
      name: "Riverboat",
      category: ["Action", "Duration"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/d8/Riverboat.jpg",
    },
    {
      name: "Root Cellar",
      category: ["Action"],
      cost: 3,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/1/16/Root_Cellar.jpg",
    },
    {
      name: "Alley",
      category: ["Action", "Shadow"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/3a/Alley.jpg",
    },
    {
      name: "Change",
      category: ["Action"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/56/Change.jpg",
    },
    {
      name: "Ninja",
      category: ["Action", "Attack", "Shadow"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/76/Ninja.jpg",
    },
    {
      name: "Poet",
      category: ["Action", "Omen"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/4/42/Poet.jpg",
    },
    {
      name: "River Shrine",
      category: ["Action", "Omen"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/b/bb/River_Shrine.jpg",
    },
    {
      name: "Rustic Village",
      category: ["Action", "Omen"],
      cost: 4,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/06/Rustic_Village.jpg",
    },
    {
      name: "Gold Mine",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/c2/Gold_Mine.jpg",
    },
    {
      name: "Imperial Envoy",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/5/5e/Imperial_Envoy.jpg",
    },
    {
      name: "Kitsune",
      category: ["Action", "Attack", "Omen"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/d/dc/Kitsune.jpg",
    },
    {
      name: "Litter",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/6/6d/Litter.jpg",
    },
    {
      name: "Rice Broker",
      category: ["Action"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/a/ac/Rice_Broker.jpg",
    },
    {
      name: "Ronin",
      category: ["Action", "Shadow"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/f/f6/Ronin.jpg",
    },
    {
      name: "Tanuki",
      category: ["Action", "Shadow"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/7/71/Tanuki.jpg",
    },
    {
      name: "Tea House",
      category: ["Action", "Omen"],
      cost: 5,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/3/39/Tea_House.jpg",
    },
    {
      name: "Samurai",
      category: ["Action", "Duration", "Attack"],
      cost: 6,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/0/0e/Samurai.jpg",
    },
    {
      name: "Rice",
      category: ["Treasure"],
      cost: 7,
      debt: 0,
      image: "https://wiki.dominionstrategy.com/images/c/cd/Rice.jpg",
    },
  ],
  events: [
    "Continue",
    "Amass",
    "Asceticism",
    "Credit",
    "Foresight",
    "Kintsugi",
    "Practice",
    "Sea Trade",
    "Receive Tribute",
    "Gather",
  ],
  prophecies: [
    "Approaching Army",
    "Biding Time",
    "Bureaucracy",
    "Divine Wind",
    "Enlightenment",
    "Flourishing Trade",
    "Good Harvest",
    "Great Leader",
    "Growth",
    "Harsh Winter",
    "Kind Emperor",
    "Panic",
    "Porgress",
    "Rapid Expansion",
    "Sickness",
  ],
};

const SETS = [
  base,
  seaside,
  prosperity,
  hinterlands,
  empires,
  allies,
  plunder,
  adventures,
  risingSun,
];
export default SETS;
