const base = {
  name: "Base",
  cards: [
    { name: "Cellar", category: ["Action"], price: 2 },
    { name: "Chapel", category: ["Action"], price: 2 },
    { name: "Moat", category: ["Action", "Reaction"], price: 2 },
    { name: "Harbinger", category: ["Action"], price: 3 },
    { name: "Merchant", category: ["Action"], price: 3 },
    { name: "Vassal", category: ["Action"], price: 3 },
    { name: "Village", category: ["Action"], price: 3 },
    { name: "Workshop", category: ["Action"], price: 3 },
    { name: "Bureaucrat", category: ["Action", "Attack"], price: 4 },
    { name: "Gardens", category: ["Victory"], price: 4 },
    { name: "Militia", category: ["Action", "Attack"], price: 4 },
    { name: "Moneylender", category: ["Action"], price: 4 },
    { name: "Poacher", category: ["Action"], price: 4 },
    { name: "Remodel", category: ["Action"], price: 4 },
    { name: "Smithy", category: ["Action"], price: 4 },
    { name: "Throne Room", category: ["Action"], price: 4 },
    { name: "Bandit", category: ["Action", "Attack"], price: 5 },
    { name: "Council Room", category: ["Action"], price: 5 },
    { name: "Festival", category: ["Action"], price: 5 },
    { name: "Laboratory", category: ["Action"], price: 5 },
    { name: "Library", category: ["Action"], price: 5 },
    { name: "Market", category: ["Action"], price: 5 },
    { name: "Mine", category: ["Action"], price: 5 },
    { name: "Sentry", category: ["Action"], price: 5 },
    { name: "Witch", category: ["Action", "Attack"], price: 5 },
    { name: "Artisan", category: ["Action"], price: 6 },
  ],
};

const seaside = {
  name: "Seaside",
  cards: [
    { name: "Haven", category: ["Action", "Duration"], price: 2 },
    { name: "Lighthouse", category: ["Action", "Duration"], price: 2 },
    { name: "Native Village", category: ["Action"], price: 2 },
    { name: "Astrolabe", category: ["Treasure", "Duration"], price: 3 },
    { name: "Fishing Village", category: ["Action"], price: 3 },
    { name: "Lookout", category: ["Action"], price: 3 },
    { name: "Monkey", category: ["Action", "Duration"], price: 3 },
    { name: "Sea Chart", category: ["Action"], price: 3 },
    { name: "Smugglers", category: ["Action"], price: 3 },
    { name: "Warehouse", category: ["Action"], price: 3 },
    { name: "Blockade", category: ["Action", "Duration", "Attack"], price: 4 },
    { name: "Caravan", category: ["Action", "Duration"], price: 4 },
    { name: "Cutpurse", category: ["Action", "Attack"], price: 4 },
    { name: "Island", category: ["Action", "Victory"], price: 4 },
    { name: "Sailor", category: ["Action", "Duration"], price: 4 },
    { name: "Salvager", category: ["Action"], price: 4 },
    { name: "Tide Pools", category: ["Action", "Duration"], price: 4 },
    { name: "Treasure Map", category: ["Action"], price: 4 },
    { name: "Bazaar", category: ["Action"], price: 5 },
    { name: "Corsaid", category: ["Action", "Duration", "Attack"], price: 5 },
    { name: "Merchant Ship", category: ["Action", "Duration"], price: 5 },
    { name: "Outpost", category: ["Action", "Duration"], price: 5 },
    { name: "Pirate", category: ["Action", "Duration", "Reaction"], price: 5 },
    { name: "Sea Witch", category: ["Action", "Duration", "Attack"], price: 5 },
    { name: "Tactician", category: ["Action", "Duration"], price: 5 },
    { name: "Treasury", category: ["Action"], price: 5 },
    { name: "Wharf", category: ["Action", "Duration"], price: 5 },
  ],
};

const prosperity = {
  name: "Prosperity",
  cards: [
    { name: "Loan", category: ["Treasure"], price: 3 },
    { name: "Trade Route", category: ["Action"], price: 3 },
    { name: "Watchtower", category: ["Action", "Reaction"], price: 3 },
    { name: "Bishop", category: ["Action"], price: 4 },
    { name: "Monument", category: ["Action"], price: 4 },
    { name: "Quarry", category: ["Treasure"], price: 4 },
    { name: "Talisman", category: ["Treasure"], price: 4 },
    { name: "Workder's Village", category: ["Action"], price: 4 },
    { name: "City", category: ["Action"], price: 5 },
    { name: "Contraband", category: ["Treasure"], price: 5 },
    { name: "Counting House", category: ["Action"], price: 5 },
    { name: "Mint", category: ["Action"], price: 5 },
    { name: "Mountebank", category: ["Action", "Attack"], price: 5 },
    { name: "Rabble", category: ["Action", "Attack"], price: 5 },
    { name: "Royal Seal", category: ["Treasure"], price: 5 },
    { name: "Vault", category: ["Action"], price: 5 },
    { name: "Venture", category: ["Treasure"], price: 5 },
    { name: "Goons", category: ["Action", "Attack"], price: 6 },
    { name: "Hoard", category: ["Treasure"], price: 6 },
    { name: "Grand Market", category: ["Action"], price: 6 },
    { name: "Bank", category: ["Treasure"], price: 7 },
    { name: "Expand", category: ["Action"], price: 7 },
    { name: "Forge", category: ["Action"], price: 7 },
    { name: "King's Court", category: ["Action"], price: 7 },
    { name: "Peddler", category: ["Action"], price: 8 },
  ],
};

const hinterlands = {
  name: "Hinterlands",
  cards: [
    { name: "Crossroads", category: ["Action"], price: 2 },
    { name: "Fool's Gold", category: ["Treasure", "Reaction"], price: 2 },
    { name: "Develop", category: ["Action"], price: 3 },
    { name: "Guard Dog", category: ["Action", "Reaction"], price: 3 },
    { name: "Oasis", category: ["Action"], price: 3 },
    { name: "Scheme", category: ["Action"], price: 3 },
    { name: "Tunnel", category: ["Victory", "Reaction"], price: 3 },
    { name: "Jack of All Trades", category: ["Action"], price: 4 },
    { name: "Nomads", category: ["Action"], price: 4 },
    { name: "Spice Merchant", category: ["Action"], price: 4 },
    { name: "Trader", category: ["Action", "Reaction"], price: 4 },
    { name: "Trail", category: ["Action", "Reaction"], price: 4 },
    { name: "Weaver", category: ["Action", "Reaction"], price: 4 },
    { name: "Berserker", category: ["Action", "Attack"], price: 5 },
    { name: "Cartographer", category: ["Action"], price: 5 },
    { name: "Cauldron", category: ["Treasure", "Attack"], price: 5 },
    { name: "Haggler", category: ["Action"], price: 5 },
    { name: "Highway", category: ["Action"], price: 5 },
    { name: "Inn", category: ["Action"], price: 5 },
    { name: "Margrave", category: ["Action", "Attack"], price: 5 },
    { name: "Souk", category: ["Action"], price: 5 },
    { name: "Stables", category: ["Action"], price: 5 },
    { name: "Wheelwright", category: ["Action"], price: 5 },
    { name: "Witch's Hut", category: ["Action", "Attack"], price: 5 },
    { name: "Border Village", category: ["Action"], price: 6 },
    { name: "Farmland", category: ["Victory"], price: 6 },
  ],
};

const empires = {
  name: "Empires",
  cards: [
    { name: "Engineer", category: ["Action"] },
    { name: "City Quarter", category: ["Action"] },
    { name: "Overlord", category: ["Action", "Command"] },
    { name: "Royal Blacksmith", category: ["Action"] },
    { name: "Encampment/Plunder", category: ["Action", "Treasure"] },
    { name: "Patrician/Emporium", category: ["Action"] },
    { name: "Settlers/Bustling Village", category: ["Action"] },
    { name: "Castles", category: ["Castle", "Victory", "Treasure", "Action"] },
    { name: "Catapult/Rocks", category: ["Action", "Attack", "Treasure"] },
    { name: "Chariot Race", category: ["Action"] },
    { name: "Enchantress", category: ["Action", "Attack", "Duration"] },
    { name: "Farmers' Market", category: ["Action", "Gathering"] },
    { name: "Gladiator/Fortune", category: ["Action", "Treasure"] },
    { name: "Sacrifice", category: ["Action"] },
    { name: "Temple", category: ["Action", "Gathering"] },
    { name: "Villa", category: ["Action"] },
    { name: "Archive", category: ["Action", "Duration"] },
    { name: "Capital", category: ["Treasure"] },
    { name: "Charm", category: ["Treasure"] },
    { name: "Crown", category: ["Action", "Treasure"] },
    { name: "Forum", category: ["Action"] },
    { name: "Groundskeeper", category: ["Action"] },
    { name: "Legionary", category: ["Action", "Attack"] },
    { name: "Wild Hunt", category: ["Action", "Gathering"] },
  ],
  events: [
    "Triumph",
    "Annex",
    "Donate",
    "Advance",
    "Delve",
    "Tax",
    "Banquet",
    "Ritual",
    "Salt the Earth",
    "Wedding",
    "Windfall",
    "Conquest",
    "Dominate",
  ],
  landmarks: [
    "Aqueduct",
    "Arena",
    "Bandit Fort",
    "Basilica",
    "Baths",
    "Battlefield",
    "Colonnade",
    "Defiled Shrine",
    "Fountain",
    "Keep",
    "Labyrinth",
    "Mountain Pass",
    "Museum",
    "Obelisk",
    "Orchard",
    "Palace",
    "Tomb",
    "Tower",
    "Triumphal Arch",
    "Wall",
    "Wolf Den",
  ],
};

const allies = {
  name: "Allies",
  cards: [
    { name: "Bauble", category: ["Treasure", "Liaison"] },
    { name: "Sycophant", category: ["Action", "Liaison"] },
    { name: "Townsfolk", category: ["Townsfolk", "Action"] },
    { name: "Augurs", category: ["Augur", "Action", "Attack"] },
    {
      name: "Clashes",
      category: ["Clash", "Action", "Attack", "Duration", "Victory"],
    },
    { name: "Forts", category: ["Fort", "Action", "Duration", "Victory"] },
    { name: "Importer", category: ["Action", "Duration", "Liaison"] },
    { name: "Merchant Campe", category: ["Action"] },
    {
      name: "Odysseys",
      category: ["Odyssey", "Action", "Duration", "Treasure", "Victory"],
    },
    { name: "Sentinel", category: ["Action"] },
    { name: "Underling", category: ["Action", "Liaison"] },
    {
      name: "Wizards",
      category: ["Wizard", "Action", "Liaison", "Duration", "Attack"],
    },
    { name: "Broker", category: ["Action", "Liaison"] },
    { name: "Carpenter", category: ["Action"] },
    { name: "Courier", category: ["Action"] },
    { name: "Innkeeper", category: ["Action"] },
    { name: "Royal Galley", category: ["Action", "Duration"] },
    { name: "Town", category: ["Action"] },
    { name: "Barbarian", category: ["Action", "Attack"] },
    { name: "Capital City", category: ["Action"] },
    { name: "Contract", category: ["Treasure", "Duration", "Liaison"] },
    { name: "Emissary", category: ["Action", "Liaison"] },
    { name: "Galleria", category: ["Action"] },
    { name: "Guildmaster", category: ["Action", "Liaison"] },
    { name: "Highwayman", category: ["Action", "Duration", "Attack"] },
    { name: "Hunter", category: ["Action"] },
    { name: "Modify", category: ["Action"] },
    { name: "Skirmisher", category: ["Action", "Attack"] },
    { name: "Specialist", category: ["Action"] },
    { name: "Swap", category: ["Action"] },
    { name: "Marquis", category: ["Action"] },
  ],
  allies: [
    "Architects' Guild",
    "Band of Nomads",
    "Cave Dwellers",
    "Circle of Witches",
    "City-state",
    "Coastal Haven",
    "Crafters' Guild",
    "Desert Guides",
    "Family of Inventors",
    "Fellowship of Scribes",
    "Forest Dwellers",
    "Gang of Pickpockets",
    "Island Folk",
    "League of Bankers",
    "League of Shopkeepers",
    "Market Towns",
    "Mountain Folk",
    "Order of Astrologers",
    "Order of Masons",
    "Peaceful Cult",
    "Plateau Shepherds",
    "Trappers' Lodge",
    "Woodworkers' Guild",
  ],
};

const plunder = {
  name: "Plunder",
  cards: [
    { name: "Cage", category: ["Treasure", "Duration"] },
    { name: "Grotto", category: ["Action", "Duration"] },
    { name: "Jewelled Egg", category: ["Treasure"] },
    { name: "Search", category: ["Action", "Duration"] },
    { name: "Shaman", category: ["Action"] },
    { name: "Secluded Shrine", category: ["Action", "Duration"] },
    { name: "Siren", category: ["Action", "Duration", "Attack"] },
    { name: "Stowaway", category: ["Action", "Duration", "Reaction"] },
    { name: "Taskmaster", category: ["Action", "Duration"] },
    { name: "Abundance", category: ["Treasure", "Duration"] },
    { name: "Cabin Boy", category: ["Action", "Duration"] },
    { name: "Crucible", category: ["Treasure"] },
    { name: "Flagship", category: ["Action", "Duration", "Command"] },
    { name: "Fortune Hunter", category: ["Action"] },
    { name: "Gondola", category: ["Treasure", "Duration"] },
    { name: "Harbor Village", category: ["Action"] },
    { name: "Landing Party", category: ["Action", "Duration"] },
    { name: "Mapmaker", category: ["Action", "Reaction"] },
    { name: "Maroon", category: ["Action"] },
    { name: "Rope", category: ["Treasure", "Duration"] },
    { name: "Swamp Shacks", category: ["Action"] },
    { name: "Tools", category: ["Treasure"] },
    { name: "Buried Treasure", category: ["Treasure", "Duration"] },
    { name: "Crew", category: ["Action", "Duration"] },
    { name: "Cutthroat", category: ["Action", "Duration", "Attack"] },
    { name: "Enlarge", category: ["Action", "Duration"] },
    { name: "Figurine", category: ["Treasure"] },
    { name: "First Mate", category: ["Action"] },
    { name: "Frigate", category: ["Action", "Duration", "Attack"] },
    { name: "Longship", category: ["Action", "Duration"] },
    { name: "Mining Road", category: ["Action"] },
    { name: "Pendant", category: ["Treasure"] },
    { name: "Pickaxe", category: ["Treasure"] },
    { name: "Pilgrim", category: ["Action"] },
    { name: "Quartermaster", category: ["Action", "Duration"] },
    { name: "Silver Mine", category: ["Treasure"] },
    { name: "Trickster", category: ["Action", "Attack"] },
    { name: "Wealthy Village", category: ["Action"] },
    { name: "Sack of Loot", category: ["Treasure"] },
    { name: "King's Cache", category: ["Treasure"] },
  ],
  events: [
    "Bury",
    "Avoid",
    "Deliver",
    "Peril",
    "Rush",
    "Foray",
    "Launch",
    "Mirror",
    "Prepare",
    "Scrounge",
    "Journey",
    "Maelstrom",
    "Looting",
    "Invasion",
    "Prosper",
  ],
  traits: [
    "Cheap",
    "Cursed",
    "Fated",
    "Fawning",
    "Friendly",
    "Hasty",
    "Inherited",
    "Inspiring",
    "Nearby",
    "Patient",
    "Pious",
    "Reckless",
    "Rich",
    "Shy",
    "Tireless",
  ],
};

const adventures = {
  name: "Adventures",
  cards: [
    { name: "Coin of the Realm", category: ["Treasure", "Reserve"] },
    { name: "Page", category: ["Action", "Traveller", "Attack", "Duration"] },
    { name: "Peasant", category: ["Action", "Traveller", "Attack", "Reserve"] },
    { name: "Ratcatcher", category: ["Action", "Reserve"] },
    { name: "Raze", category: ["Action"] },
    { name: "Amulet", category: ["Action", "Duration"] },
    { name: "Caravan Guard", category: ["Action", "Duration", "Reaction"] },
    { name: "Dungeon", category: ["Action", "Duration"] },
    { name: "Gear", category: ["Action", "Duration"] },
    { name: "Guide", category: ["Action", "Reserve"] },
    { name: "Duplicate", category: ["Action", "Reserve"] },
    { name: "Magpie", category: ["Action"] },
    { name: "Messenger", category: ["Action"] },
    { name: "Miser", category: ["Action"] },
    { name: "Port", category: ["Action"] },
    { name: "Ranger", category: ["Action"] },
    { name: "Transmogrify", category: ["Action", "Reserve"] },
    { name: "Artificer", category: ["Action"] },
    { name: "Bridge Troll", category: ["Action", "Duration", "Attack"] },
    { name: "Distant Lands", category: ["Action", "Reserve", "Victory"] },
    { name: "Giant", category: ["Action", "Attack"] },
    { name: "Haunted Woods", category: ["Action", "Duration", "Attack"] },
    { name: "Lost City", category: ["Action"] },
    { name: "Relic", category: ["Treasure", "Attack"] },
    { name: "Royal Carriage", category: ["Action", "Reserve"] },
    { name: "Storyteller", category: ["Action"] },
    { name: "Swamp Hag", category: ["Action", "Duration", "Attack"] },
    { name: "Treasure Trove", category: ["Treasure"] },
    { name: "Wine Merchant", category: ["Action", "Reserve"] },
    { name: "Hireling", category: ["Action", "Duration"] },
  ],
  events: [
    "Alms",
    "Borrow",
    "Quest",
    "Save",
    "Scouting Party",
    "Travelling Fair",
    "Bonfire",
    "Expedition",
    "Ferry",
    "Plan",
    "Mission",
    "Pilgrimage",
    "Ball",
    "Raid",
    "Seaway",
    "Trade",
    "Lost Arts",
    "Training",
    "Inheritance",
    "Pathfinding",
  ],
};

const risingSun = {
  name: "Rising Sun",
  cards: [
    { name: "Mountain Shrine", category: ["Action", "Omen"] },
    { name: "Daimyo", category: ["Action", "Command"] },
    { name: "Artist", category: ["Action"] },
    { name: "Fishmonger", category: ["Action", "Shadow"] },
    { name: "Snake Witch", category: ["Action", "Attack"] },
    { name: "Aristocrat", category: ["Action"] },
    { name: "Craftsman", category: ["Action"] },
    { name: "Riverboat", category: ["Action", "Duration"] },
    { name: "Root Cellar", category: ["Action"] },
    { name: "Alley", category: ["Action", "Shadow"] },
    { name: "Change", category: ["Action"] },
    { name: "Ninja", category: ["Action", "Attack", "Shadow"] },
    { name: "Poet", category: ["Action", "Omen"] },
    { name: "River Shrine", category: ["Action", "Omen"] },
    { name: "Rustic Village", category: ["Action", "Omen"] },
    { name: "Gold Mine", category: ["Action"] },
    { name: "Imperial Envoy", category: ["Action"] },
    { name: "Kitsune", category: ["Action", "Attack", "Omen"] },
    { name: "Litter", category: ["Action"] },
    { name: "Rice Broker", category: ["Action"] },
    { name: "Ronin", category: ["Action", "Shadow"] },
    { name: "Tanuki", category: ["Action", "Shadow"] },
    { name: "Tea House", category: ["Action", "Omen"] },
    { name: "Samurai", category: ["Action", "Duration", "Attack"] },
    { name: "Rice", category: ["Treasure"] },
  ],
  events: [
    "Continue",
    "Amass",
    "Asceticism",
    "Credit",
    "Foresight",
    "Kintsugi",
    "Practice",
    "Sea Trade",
    "Receive Tribute",
    "Gather",
  ],
  prophecies: [
    "Approaching Army",
    "Biding Time",
    "Bureaucracy",
    "Divine Wind",
    "Enlightenment",
    "Flourishing Trade",
    "Good Harvest",
    "Great Leader",
    "Growth",
    "Harsh Winter",
    "Kind Emperor",
    "Panic",
    "Porgress",
    "Rapid Expansion",
    "Sickness",
  ],
};

const SETS = [
  base,
  seaside,
  prosperity,
  hinterlands,
  empires,
  allies,
  plunder,
  adventures,
  risingSun,
];
export default SETS;
